DROP TABLE filter;
CREATE TABLE "filter" ("id"  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,"platform"  INTEGER NOT NULL DEFAULT 0,"type"  TEXT NOT NULL,"name"  TEXT NOT NULL DEFAULT '');
ALTER TABLE menu ADD COLUMN "sort" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE platform ADD COLUMN "title_path" TEXT NOT NULL DEFAULT '';
ALTER TABLE platform ADD COLUMN "background_path" TEXT NOT NULL DEFAULT '';
ALTER TABLE platform ADD COLUMN "doc_path" TEXT NOT NULL DEFAULT '';
ALTER TABLE platform ADD COLUMN "rombase" TEXT NOT NULL DEFAULT '';
ALTER TABLE platform ADD COLUMN "cassette_path"  TEXT NOT NULL DEFAULT '';
ALTER TABLE platform ADD COLUMN "icon_path"  TEXT NOT NULL DEFAULT '';
ALTER TABLE platform ADD COLUMN "gif_path"  TEXT NOT NULL DEFAULT '';
ALTER TABLE platform ADD COLUMN "files_path"  TEXT NOT NULL DEFAULT '';
ALTER TABLE simulator ADD COLUMN "sort" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE simulator ADD COLUMN "lua" TEXT NOT NULL DEFAULT '';
ALTER TABLE rom ADD COLUMN "base_version" TEXT NOT NULL,
ALTER TABLE config ADD COLUMN "romlist_font_size" TEXT NOT NULL DEFAULT '';
CREATE TABLE "rombase_enum" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,"type" TEXT NOT NULL DEFAULT '',"name" TEXT NOT NULL DEFAULT '');
INSERT INTO "rombase_enum" VALUES (1, 'publisher', 'NINTENDO');
INSERT INTO "rombase_enum" VALUES (2, 'publisher', 'FALCOM');
INSERT INTO "rombase_enum" VALUES (3, 'publisher', 'CAPCOM');
INSERT INTO "rombase_enum" VALUES (4, 'publisher', 'SQUARE');
INSERT INTO "rombase_enum" VALUES (5, 'publisher', 'SNK');
INSERT INTO "rombase_enum" VALUES (6, 'publisher', 'SEGA');
INSERT INTO "rombase_enum" VALUES (7, 'publisher', 'KONAMI');
INSERT INTO "rombase_enum" VALUES (8, 'publisher', 'TECHNŌS');
INSERT INTO "rombase_enum" VALUES (9, 'publisher', 'TAITO');
INSERT INTO "rombase_enum" VALUES (10, 'publisher', 'BANDAI');
INSERT INTO "rombase_enum" VALUES (11, 'publisher', 'IGS');
INSERT INTO "rombase_enum" VALUES (12, 'publisher', 'DATA EAST');
INSERT INTO "rombase_enum" VALUES (13, 'publisher', 'DISNEY');
INSERT INTO "rombase_enum" VALUES (14, 'publisher', 'KOEI');
INSERT INTO "rombase_enum" VALUES (15, 'country', '中国');
INSERT INTO "rombase_enum" VALUES (16, 'country', '丹麦');
INSERT INTO "rombase_enum" VALUES (17, 'country', '荷兰');
INSERT INTO "rombase_enum" VALUES (18, 'country', '英国');
INSERT INTO "rombase_enum" VALUES (19, 'country', '芬兰');
INSERT INTO "rombase_enum" VALUES (20, 'country', '法国');
INSERT INTO "rombase_enum" VALUES (21, 'country', '德国');
INSERT INTO "rombase_enum" VALUES (22, 'country', '意大利');
INSERT INTO "rombase_enum" VALUES (23, 'country', '日本');
INSERT INTO "rombase_enum" VALUES (24, 'country', '韩国');
INSERT INTO "rombase_enum" VALUES (25, 'country', '挪威');
INSERT INTO "rombase_enum" VALUES (26, 'country', '波兰');
INSERT INTO "rombase_enum" VALUES (27, 'country', '葡萄牙');
INSERT INTO "rombase_enum" VALUES (28, 'country', '西班牙');
INSERT INTO "rombase_enum" VALUES (29, 'type', 'ACT(动作过关)');
INSERT INTO "rombase_enum" VALUES (30, 'type', 'RPG(角色扮演)');
INSERT INTO "rombase_enum" VALUES (31, 'type', 'FTG(格斗)');
INSERT INTO "rombase_enum" VALUES (32, 'type', 'RAC(赛车)');
INSERT INTO "rombase_enum" VALUES (33, 'type', 'SLG(策略)');
INSERT INTO "rombase_enum" VALUES (34, 'type', 'SPT(体育)');
INSERT INTO "rombase_enum" VALUES (35, 'type', 'STG(飞行射击)');
INSERT INTO "rombase_enum" VALUES (36, 'type', 'TAB(桌面)');
INSERT INTO "rombase_enum" VALUES (37, 'type', 'PUZ(益智休闲)');
INSERT INTO "rombase_enum" VALUES (38, 'type', 'FPS(第一人称射击)');
INSERT INTO "rombase_enum" VALUES (39, 'type', 'LGG(光枪游戏)');
INSERT INTO "rombase_enum" VALUES (40, 'type', 'MSC(音乐)');
INSERT INTO "rombase_enum" VALUES (41, 'version', '美版');
INSERT INTO "rombase_enum" VALUES (42, 'version', '日版');
INSERT INTO "rombase_enum" VALUES (43, 'version', '欧版');
INSERT INTO "rombase_enum" VALUES (44, 'version', '世界版');
INSERT INTO "rombase_enum" VALUES (45, 'version', '盗版');
