DROP TABLE filter;
CREATE TABLE "filter" ("id"  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,"platform"  INTEGER NOT NULL DEFAULT 0,"type"  TEXT NOT NULL,"name"  TEXT NOT NULL DEFAULT '');
ALTER TABLE config ADD COLUMN "panel_platform_width" TEXT NOT NULL DEFAULT '',
ALTER TABLE config ADD COLUMN "panel_menu_width" TEXT NOT NULL DEFAULT '',
ALTER TABLE config ADD COLUMN "panel_sidebar_width" TEXT NOT NULL DEFAULT '',
ALTER TABLE config DROP COLUMN rename_type;
ALTER TABLE menu ADD COLUMN "sort" INTEGER NOT NULL DEFAULT 0
ALTER TABLE platform ADD COLUMN "title_path" TEXT NOT NULL DEFAULT '',
ALTER TABLE platform ADD COLUMN "background_path" TEXT NOT NULL DEFAULT '',
ALTER TABLE platform ADD COLUMN "doc_path" TEXT NOT NULL DEFAULT '',
ALTER TABLE platform ADD COLUMN "rombase" TEXT NOT NULL DEFAULT '',
ALTER TABLE platform DROP COLUMN romlist;
ALTER TABLE rom ADD COLUMN "base_type" TEXT NOT NULL DEFAULT '',
ALTER TABLE rom ADD COLUMN "base_year" TEXT NOT NULL DEFAULT '',
ALTER TABLE rom ADD COLUMN "base_publisher" TEXT NOT NULL DEFAULT '',
ALTER TABLE rom ADD COLUMN "base_country" TEXT NOT NULL DEFAULT '',
ALTER TABLE simulator ADD COLUMN "sort" INTEGER NOT NULL DEFAULT 0